server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hand-demo
    username: admin
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    secret-key: 3MP8Xi8ExjXcPHbOO3wWLRHJDGqwK6XV
    jwt-ttl: 300000 # 5 minutes

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG